user_token: OTY3NmVjYWYtZTJhNC00NzNhLTgwM2YtZGY3OTBkYTM3YWFhXzY5Mjc=

session:
  key: CaY5iCkYtN7DqXdiYK1BvmGrQuaSA4Tl4bEk9my0jc0=
admin:
  email: admin@admin.com
  password: admin
database:
  host: localhost
  port: 5432
  user: kts_user
  password: kts_pass
  database: kts
bot:
  token: vk1.a.UEASNzixaQkV4jbzXay3wqdSy8heT3yXWQhU2_dimhNpejzCqBfzkc5Y_vVJklANuzJOm_2z8q2Fqk2A-iPU8Ft1o7xvuvIejSbaCcuH96tpda0Qii8UdKXHPgWX3imrG1uhaJgRzCEvl9-E2Ae4ibdiIPao6w7JWfaT39WJtaeFGmEJKYSWvtJCW8nvqQBA-0M61zyZFa0tddTBCuXrpA
  group_id: 218897004


